# Generated by Django 3.0.1 on 2020-01-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('hostelname', models.CharField(max_length=100)),
                ('roomno', models.CharField(max_length=100)),
                ('contectno', models.CharField(max_length=100)),
            ],
        ),
    ]
