# Generated by Django 3.0.1 on 2020-01-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='xeroxdetails',
        ),
    ]
