# Generated by Django 3.0.1 on 2020-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200105_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroxdetails',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
