# Generated by Django 3.0.1 on 2020-01-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_xeroxdetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xeroxdetails',
            name='image',
        ),
    ]
